// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/hello.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HelloServiceClient is the client API for HelloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloServiceClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	ServerStreaming(ctx context.Context, in *Names, opts ...grpc.CallOption) (HelloService_ServerStreamingClient, error)
	ClientStreaming(ctx context.Context, opts ...grpc.CallOption) (HelloService_ClientStreamingClient, error)
	BiDirectionalStreaming(ctx context.Context, opts ...grpc.CallOption) (HelloService_BiDirectionalStreamingClient, error)
}

type helloServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloServiceClient(cc grpc.ClientConnInterface) HelloServiceClient {
	return &helloServiceClient{cc}
}

func (c *helloServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/hello.HelloService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloServiceClient) ServerStreaming(ctx context.Context, in *Names, opts ...grpc.CallOption) (HelloService_ServerStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &HelloService_ServiceDesc.Streams[0], "/hello.HelloService/ServerStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloServiceServerStreamingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HelloService_ServerStreamingClient interface {
	Recv() (*HelloResponse, error)
	grpc.ClientStream
}

type helloServiceServerStreamingClient struct {
	grpc.ClientStream
}

func (x *helloServiceServerStreamingClient) Recv() (*HelloResponse, error) {
	m := new(HelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *helloServiceClient) ClientStreaming(ctx context.Context, opts ...grpc.CallOption) (HelloService_ClientStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &HelloService_ServiceDesc.Streams[1], "/hello.HelloService/ClientStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloServiceClientStreamingClient{stream}
	return x, nil
}

type HelloService_ClientStreamingClient interface {
	Send(*HelloRequest) error
	CloseAndRecv() (*Messages, error)
	grpc.ClientStream
}

type helloServiceClientStreamingClient struct {
	grpc.ClientStream
}

func (x *helloServiceClientStreamingClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *helloServiceClientStreamingClient) CloseAndRecv() (*Messages, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Messages)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *helloServiceClient) BiDirectionalStreaming(ctx context.Context, opts ...grpc.CallOption) (HelloService_BiDirectionalStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &HelloService_ServiceDesc.Streams[2], "/hello.HelloService/BiDirectionalStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloServiceBiDirectionalStreamingClient{stream}
	return x, nil
}

type HelloService_BiDirectionalStreamingClient interface {
	Send(*HelloRequest) error
	Recv() (*HelloResponse, error)
	grpc.ClientStream
}

type helloServiceBiDirectionalStreamingClient struct {
	grpc.ClientStream
}

func (x *helloServiceBiDirectionalStreamingClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *helloServiceBiDirectionalStreamingClient) Recv() (*HelloResponse, error) {
	m := new(HelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HelloServiceServer is the server API for HelloService service.
// All implementations must embed UnimplementedHelloServiceServer
// for forward compatibility
type HelloServiceServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	ServerStreaming(*Names, HelloService_ServerStreamingServer) error
	ClientStreaming(HelloService_ClientStreamingServer) error
	BiDirectionalStreaming(HelloService_BiDirectionalStreamingServer) error
	mustEmbedUnimplementedHelloServiceServer()
}

// UnimplementedHelloServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHelloServiceServer struct {
}

func (UnimplementedHelloServiceServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedHelloServiceServer) ServerStreaming(*Names, HelloService_ServerStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerStreaming not implemented")
}
func (UnimplementedHelloServiceServer) ClientStreaming(HelloService_ClientStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientStreaming not implemented")
}
func (UnimplementedHelloServiceServer) BiDirectionalStreaming(HelloService_BiDirectionalStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method BiDirectionalStreaming not implemented")
}
func (UnimplementedHelloServiceServer) mustEmbedUnimplementedHelloServiceServer() {}

// UnsafeHelloServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloServiceServer will
// result in compilation errors.
type UnsafeHelloServiceServer interface {
	mustEmbedUnimplementedHelloServiceServer()
}

func RegisterHelloServiceServer(s grpc.ServiceRegistrar, srv HelloServiceServer) {
	s.RegisterService(&HelloService_ServiceDesc, srv)
}

func _HelloService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.HelloService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelloService_ServerStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Names)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HelloServiceServer).ServerStreaming(m, &helloServiceServerStreamingServer{stream})
}

type HelloService_ServerStreamingServer interface {
	Send(*HelloResponse) error
	grpc.ServerStream
}

type helloServiceServerStreamingServer struct {
	grpc.ServerStream
}

func (x *helloServiceServerStreamingServer) Send(m *HelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _HelloService_ClientStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelloServiceServer).ClientStreaming(&helloServiceClientStreamingServer{stream})
}

type HelloService_ClientStreamingServer interface {
	SendAndClose(*Messages) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type helloServiceClientStreamingServer struct {
	grpc.ServerStream
}

func (x *helloServiceClientStreamingServer) SendAndClose(m *Messages) error {
	return x.ServerStream.SendMsg(m)
}

func (x *helloServiceClientStreamingServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _HelloService_BiDirectionalStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelloServiceServer).BiDirectionalStreaming(&helloServiceBiDirectionalStreamingServer{stream})
}

type HelloService_BiDirectionalStreamingServer interface {
	Send(*HelloResponse) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type helloServiceBiDirectionalStreamingServer struct {
	grpc.ServerStream
}

func (x *helloServiceBiDirectionalStreamingServer) Send(m *HelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *helloServiceBiDirectionalStreamingServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HelloService_ServiceDesc is the grpc.ServiceDesc for HelloService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelloService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hello.HelloService",
	HandlerType: (*HelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _HelloService_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerStreaming",
			Handler:       _HelloService_ServerStreaming_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ClientStreaming",
			Handler:       _HelloService_ClientStreaming_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BiDirectionalStreaming",
			Handler:       _HelloService_BiDirectionalStreaming_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/hello.proto",
}
